name: Deploy ssr-editor-frontend App to GitHub Pages

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    - name: Set up Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 22
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: npm run build
    - name: Serve production build
      run: npx serve -s dist -l 5173 --single &
    - name: Wait for server
      run: npx wait-on http://localhost:5173/ssr-editor-frontend/create
    - name: Run Cypress tests
      run: npx cypress run
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist
        publish_branch: gh-pages